In [5]:
import pandas as pd

order = pd.read_excel('/content/orderitems(may_june_july).xlsx')
order
tickets = pd.read_excel('/content/ticket(june_july).xlsx')
#tickets

In [6]:
order

,id,order_id,product_id,product_flavor_id,store_id,product_title,memory,color,qty,gift,price,retailer_price,total_price,imei_number,date_create,date_modify
0,1273755,1057544,7667,16236,9999,Samsung Galaxy S24 Ultra,512gb - 12gb ram,titanium_yellow,1,NaN,413999,434999,413999,NaN,2024-05-01 00:00:34,2024-05-01 00:00:34
1,1273756,1057545,6640,13653,9999,Xiaomi Redmi Note 12,128gb - 8gb ram,onyx_gray,1,NaN,43699,48999,43699,864595070843200,2024-05-01 00:01:16,2024-05-02 17:37:48
2,1273757,1057546,7579,16035,9999,YOLO Ultron Smart Watch,0,silver,1,NaN,7699,17999,7699,khi-apr-2262,2024-05-01 00:01:23,2024-05-02 16:01:12
3,1273758,1057547,6614,13608,9999,T10 Ultra Bluetooth Calling Watch,0,black,1,NaN,1749,3999,1749,LHE-37907,2024-05-01 00:01:46,2024-05-02 14:23:24
4,1273759,1057548,7710,16381,9999,Xiaomi Redmi Note 13,256gb - 8gb ram,ice_blue,1,NaN,50999,54999,50999,868886077453317,2024-05-01 00:01:52,2024-05-02 14:30:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166518,1444023,1223283,7890,16741,9999,UMIDIGI A15,256gb - 8gb ram,space_grey,1,NaN,37299,42999,37299,NaN,2024-07-29 17:20:51,2024-07-29 17:20:51
166519,1444024,1223284,7710,16381,9999,Xiaomi Redmi Note 13,256gb - 8gb ram,ice_blue,1,NaN,52999,57999,52999,NaN,2024-07-29 17:21:27,2024-07-29 17:21:27
166520,1444025,1223285,7714,16359,9999,Xiaomi Redmi Note 13 Pro,512gb - 12gb ram,forest_green,1,NaN,82999,89999,82999,NaN,2024-07-29 17:24:11,2024-07-29 17:24:11
166521,1444026,1223286,6194,12821,9999,M10 TWS Wireless Bluetooth Earbuds,0,black,1,NaN,949,2499,949,NaN,2024-07-29 17:24:39,2024-07-29 17:24:39
166522,1444027,1223287,8349,17787,9999,GFive 6700 4G (2024),16gb - 2gb ram,copper,1,NaN,7199,8000,7199,NaN,2024-07-29 17:25:03,2024-07-29 17:25:03

In [2]:
"""import pandas as pd

# Load the datasets
ticket = pd.read_excel('/content/Ticket_Center(June).xlsx')
pr_cat = pd.read_excel('/content/Product_Category.xlsx')

# Inspect column names
print("Ticket columns:", ticket.columns)
print("Product Category columns:", pr_cat.columns)

# Adjust column names if necessary (uncomment and edit if needed)
# pr_cat.rename(columns={'old_id_column_name': 'id'}, inplace=True)
# ticket.rename(columns={'old_category_id_column_name': 'category_id'}, inplace=True)

# Merge ticket with pr_cat on category_id and id
orders_with_names = ticket.merge(pr_cat[['id', 'name']], left_on='category_id', right_on='id', how='left')

# Drop the original category_id and id columns
orders_with_names = orders_with_names.drop(columns=['category_id', 'id'])

# Rename the 'name' column to 'category_name'
orders_with_names = orders_with_names.rename(columns={'name': 'category_name'})

# Display the updated orders dataset
print(orders_with_names)
"""

'import pandas as pd\n\n# Load the datasets\nticket = pd.read_excel(\'/content/Ticket_Center(June).xlsx\')\npr_cat = pd.read_excel(\'/content/Product_Category.xlsx\')\n\n# Inspect column names\nprint("Ticket columns:", ticket.columns)\nprint("Product Category columns:", pr_cat.columns)\n\n# Adjust column names if necessary (uncomment and edit if needed)\n# pr_cat.rename(columns={\'old_id_column_name\': \'id\'}, inplace=True)\n# ticket.rename(columns={\'old_category_id_column_name\': \'category_id\'}, inplace=True)\n\n# Merge ticket with pr_cat on category_id and id\norders_with_names = ticket.merge(pr_cat[[\'id\', \'name\']], left_on=\'category_id\', right_on=\'id\', how=\'left\')\n\n# Drop the original category_id and id columns\norders_with_names = orders_with_names.drop(columns=[\'category_id\', \'id\'])\n\n# Rename the \'name\' column to \'category_name\'\norders_with_names = orders_with_names.rename(columns={\'name\': \'category_name\'})\n\n# Display the updated orders dataset\nprint(orders_with_names)\n'

In [3]:


# Get the unique subjects from the tickets dataset
ticket_subjects = tickets['subject'].unique()

# Filter the orders dataset based on the order_id matching the subjects from tickets
back_orders = order[order['order_id'].isin(ticket_subjects)]

# Display the back_orders dataset
back_orders

,id,order_id,product_id,product_flavor_id,store_id,product_title,memory,color,qty,gift,price,retailer_price,total_price,imei_number,date_create,date_modify
522,1274293,1058082,7531,15919,9999,Samsung Galaxy Tab A9Plus (X210),64gb - 4gb ram,gray,1,NaN,53999,75000,53999,R9TWB06TZ9P,2024-05-01 11:25:24,2024-05-02 13:13:22
1871,1275686,1059475,6746,15083,9999,Itel S23 4G,256gb - 16gb ram,mystery_white,1,NaN,23099,24999,23099,357201934232201,2024-05-01 22:34:49,2024-05-02 20:12:02
2317,1276151,1059939,7391,15589,9999,Tecno Pova 5 Pro,256gb - 8gb ram,dark_illusion,1,NaN,38199,44999,38199,359599881038721,2024-05-02 09:29:16,2024-05-02 17:42:33
3026,1276884,1060613,6640,13653,9999,Xiaomi Redmi Note 12,128gb - 8gb ram,onyx_gray,1,NaN,43699,48999,43699,864595070823087,2024-05-02 15:14:59,2024-05-02 16:39:55
3205,1277069,1060791,6568,13520,9999,Infinix XE22 Wireless Earbuds,0,white,1,NaN,2999,4999,2999,15012305054428,2024-05-02 16:29:00,2024-05-02 20:35:43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164142,1441614,1220952,6194,12821,9999,M10 TWS Wireless Bluetooth Earbuds,0,black,1,NaN,949,2499,949,I-JUL24-2436,2024-07-28 08:39:50,2024-07-29 12:33:48
164333,1441808,1221142,8312,17670,9999,Samsung Galaxy A55 5G,256gb - 8gb ram,awesome_lilac,1,NaN,135999,139999,135999,NaN,2024-07-28 11:55:37,2024-07-28 11:55:37
164547,1442023,1221355,7600,16092,9999,Motorola Moto G84 5G,256gb - 12gb ram,marshmallow_blue,1,NaN,67999,74999,67999,350162399678634,2024-07-28 14:24:28,2024-07-29 15:26:10
164790,1442273,1221600,8379,17947,9999,Xiaomi Redmi 13,128gb - 8gb ram,ocean_blue,1,NaN,37999,42999,37999,NaN,2024-07-28 16:45:00,2024-07-28 16:45:00
165181,1442670,1221994,7715,16367,9999,Xiaomi Redmi Note 13 Pro Plus,512gb - 12gb ram,aurora_purple,1,NaN,131999,139999,131999,NaN,2024-07-28 21:01:39,2024-07-28 21:01:39

In [7]:
import pandas as pd

# Assuming tickets and order are already defined pandas DataFrames

# Step 1: Get the unique subjects from the tickets dataset
ticket_subjects = tickets['subject'].unique()

# Step 2: Filter the orders dataset based on the order_id matching the subjects from tickets
back_orders = order[order['order_id'].isin(ticket_subjects)]

# Step 3: Extract the id column from the tickets dataset and rename it to 'ticket_id'
ticket_ids = tickets[tickets['subject'].isin(ticket_subjects)][['id', 'subject']]
ticket_ids = ticket_ids.rename(columns={'id': 'ticket_id', 'subject': 'order_id'})

# Step 4: Merge the extracted ticket ids with the filtered orders dataset
back_orders = pd.merge(back_orders, ticket_ids, on='order_id', how='left')

# Display the back_orders dataset
back_orders

,id,order_id,product_id,product_flavor_id,store_id,product_title,memory,color,qty,gift,price,retailer_price,total_price,imei_number,date_create,date_modify,ticket_id
0,1274293,1058082,7531,15919,9999,Samsung Galaxy Tab A9Plus (X210),64gb - 4gb ram,gray,1,NaN,53999,75000,53999,R9TWB06TZ9P,2024-05-01 11:25:24,2024-05-02 13:13:22,52506
1,1275686,1059475,6746,15083,9999,Itel S23 4G,256gb - 16gb ram,mystery_white,1,NaN,23099,24999,23099,357201934232201,2024-05-01 22:34:49,2024-05-02 20:12:02,53617
2,1276151,1059939,7391,15589,9999,Tecno Pova 5 Pro,256gb - 8gb ram,dark_illusion,1,NaN,38199,44999,38199,359599881038721,2024-05-02 09:29:16,2024-05-02 17:42:33,52186
3,1276884,1060613,6640,13653,9999,Xiaomi Redmi Note 12,128gb - 8gb ram,onyx_gray,1,NaN,43699,48999,43699,864595070823087,2024-05-02 15:14:59,2024-05-02 16:39:55,50350
4,1277069,1060791,6568,13520,9999,Infinix XE22 Wireless Earbuds,0,white,1,NaN,2999,4999,2999,15012305054428,2024-05-02 16:29:00,2024-05-02 20:35:43,50762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5077,1441614,1220952,6194,12821,9999,M10 TWS Wireless Bluetooth Earbuds,0,black,1,NaN,949,2499,949,I-JUL24-2436,2024-07-28 08:39:50,2024-07-29 12:33:48,55461
5078,1441808,1221142,8312,17670,9999,Samsung Galaxy A55 5G,256gb - 8gb ram,awesome_lilac,1,NaN,135999,139999,135999,NaN,2024-07-28 11:55:37,2024-07-28 11:55:37,55458
5079,1442023,1221355,7600,16092,9999,Motorola Moto G84 5G,256gb - 12gb ram,marshmallow_blue,1,NaN,67999,74999,67999,350162399678634,2024-07-28 14:24:28,2024-07-29 15:26:10,55477
5080,1442273,1221600,8379,17947,9999,Xiaomi Redmi 13,128gb - 8gb ram,ocean_blue,1,NaN,37999,42999,37999,NaN,2024-07-28 16:45:00,2024-07-28 16:45:00,55484
5081,1442670,1221994,7715,16367,9999,Xiaomi Redmi Note 13 Pro Plus,512gb - 12gb ram,aurora_purple,1,NaN,131999,139999,131999,NaN,2024-07-28 21:01:39,2024-07-28 21:01:39,55489

In [8]:
back_orders.to_excel('Tickets_of_June_and_July_with_categories.xlsx', index  = False)